# nginx proxy address - http://172.17.0.1:8105

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  cosmos:
    image: azukaar/cosmos-server:latest
    container_name: cosmos-app
    restart: unless-stopped
    logging: *default-logging
    networks:
      - cosmos
    ports:
      - "8105:80"
    environment:
      TZ: ${TZ:-America/New_York}
    volumes:
      - ./volumes/config/cosmos:/config
      - ./volumes/data/cosmos:/data

networks:
  cosmos:
    external: false
